### ISSUE TITLE
uniqtype-make-precise test failure

### ISSUE THREAD

**Issue by jryans** [stephenrkell/liballocs#41]
On Ubuntu 18.04.2, uniqtype-make-precise fails with the stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555555560de in main () at uniqtype-make-precise.c:27
```

It looks like `make_precise` is null.

**Comment by jryans** [comment]
Aha, good to hear more about how array lengths are handled. I agree it seems best to remove distinct types per length in the future.

Your fix is working here as well, thanks! :grin:
